[package]
name = "bubshayz/comet"
version = "4.1.1"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.5.0"
network = "bubshayz/network@6.2.0"